# https://taskfile.dev

version: "3"

vars:
    FILES: "main.js styles.css manifest.json"
    VERSION:
        sh: node -e "console.log(require('./package.json').version)"

tasks:
    default: task -a

    dev: npm run dev

    build: npm run build

    bump:
        cmds:
            - npm version minor
            - npm run version

    release:
        cmds:
            - git add .
            - git commit -m "{{.VERSION}} Commit"
            - git tag {{.VERSION}}
            - git push
            - git push --tags
            - task: release-create

    release-create:
        cmds:
            - gh release create {{.VERSION}} --title "{{.VERSION}}" --notes "New release of the Web Bookmarks plugin for Obsidian." {{.FILES}}

    test:
        cmds:
            - echo {{.VERSION}}
